name: bases
description: A flutter app that converts between numerical bases.

publish_to: "none"
version: 1.0.6

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  b: ^0.1.1+1
  window_manager: ^0.2.0
  numerus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
